world_fn: "/worlds/trees"

# velo/avia/mid360
lidar_types: ["velo", "avia", "avia"]
lidar_topics: ["velo1", "avia1", "avia2"]
# lidar_types: ["avia"]
# lidar_topics: ["avia1"]
odom_topic: "odom"

# from base to liadr, xyzw-xyz
# exts: [0, 0, 1, 0, 0, 0, 0.5]
exts: [0, 0.258819, 0, 0.965926, 0, 0, 0.1, 
      0, 0, 1, 0, 0, 0, 0.5, 
      0, 0, 0.707107, 0.707107, 0, 0.1, 0]

path:
    dt: 0.1
    path_fn: "/path_dir/path_line.txt"
    total_time: 4.0

lidar_info:

    hz: 10
    range: [0.1, 200.0]
    dist_noise: 0.01

    velo:
        ver_range: [-15, 15]
        hor_range: [0, 360]
        
        ver_sample: 16
        hor_sample: 1800

    livox:
        pc_type: "pc2"  # or "livox"
        scan_dir: "/doc/scan_mode/"
        samples: 24000

out_bag: "/bag/velo.bag"
    