world_fn: "/worlds/shape"

# velo/avia/mid360
lidar_types: ["velo"]
lidar_topics: ["velo1"]
odom_topic: "/odom"

# from base to liadr, xyzw-xyz
exts: [0, 0, 0, 1, 0, 0, 0]

path:
    dt: 0.1
    path_fn: "/path_dir/path_line.txt"
    total_time: 4.0

lidar_info:

    hz: 10
    range: [0.1, 200.0]
    dist_noise: 0.01

    velo:
        ver_ang: []
        ver_range: [-15, 15]
        hor_range: [0, 360]
        
        ver_sample: 16
        hor_sample: 1800

    livox:
        scan_dir: "/doc/scan_mode/avia.csv"
        samples: 24000

out_bag: "/bag/velo.bag"



    