# task surppor shot or record or mkpm
task: "record"

world_fn: "/worlds/notree"
# world_fn: "/worlds/room.world"

# velo/avia/mid360
# lidar_types: ["velo", "avia", "avia"]
# lidar_topics: ["velo1", "avia1", "avia2"]
# lidar_types: ["velo", "avia"]
# lidar_topics: ["velo1", "avia1"]

cam_yml: "/config/cams.yaml"
# cam_yml: ""

imu_yml: "/config/imus.yaml"

# make 5 lidar datasets
# lidar_types: ["avia", "avia", "velo", "velo", "avia"]
# lidar_topics: ["avia1", "avia2", "velo1", "velo2", "avia3"]

lidar_types: ["avia"]
lidar_topics: ["avia1"]
odom_topic: "odom"
gt_odom_topic: "gt_odom"

# from base to liadr, xyzw-xyz
exts: [0, 0, 0, 1, 0, 0, 0.1]
# exts: [0, 0.258819, 0, 0.965926, 0, 0, 0.1, 
#       0, 0, 1, 0, 0, 0, 0.5]
      # 0, 0, 0.707107, 0.707107, 0, 0.1, 0]

# 5 lidar exts
# exts: [0,-0.173648,0,0.984808,0.1,0,0,
#        0.153046,0.153046,0.690346,0.690346,0,0.1,0,
#        -0.087156,0,0.996195,0,-0.1,0,0,
#        -0.092296,0.092296,-0.701057,0.701057,0,-0.1,0,
#        0,0,0,1,0,0,0.2]

path:
    dt: 0.1
    path_fn: "/path_dir/path8.txt"
    total_time: 8.0

lidar_info:

    hz: 10
    range: [0.1, 200.0]
    dist_noise: 0.01

    velo:
        ver_range: [-15, 15]
        hor_range: [0, 360]
        
        ver_sample: 16
        hor_sample: 1800

    livox:
        pc_type: "pc2"  # or "livox"
        scan_dir: "/doc/scan_mode/"
        samples: 24000

# out_bag: "/bag/velo.bag"
# out_bag: "/bag/fivelids.bag"
out_bag: "/bag/pcrgb.bag"

odom_noise: [0.5, 0.05]


shot:
    # tum format
    # timestamp x y z q_x q_y q_z q_w
    shot_dir: "/home/rick/chore/obj6dof/pcd/pm/tum/"
    shot_fn: "shot.txt"

mkpm:
    lidar_type: mid360
    mkpm_dir: "/home/rick/chore/obj6dof/pcd/pm/"
    # mkpm_fn: "tum/mkpm.txt"
    mkpm_fn: "tum/origin.txt"
    num_each_loc: 5
    ds: 0.1
    save_fn: "../tree_rgb.pcd"

    stain:
        enable: true
        text_size: 720
        cm_fn: "tum/cmtree.txt"

